#!/bin/bash
# Sample Administration menu
echo 'select a task: '
select TASK in 'Checks mounts' 'Check Disk Space' 'Check Memory Usage'  # These are the options

do

        case $REPLY in 
            1 ) TASK=mount;;
            2 ) TASK="df -h";;
            3 ) TASK="free -m";;        # free not avalible on Mash
            * ) echo ERROR && exit 2;;
        esac
        
        if [ -n "$TASK" ]
            then
                    clear
                    $TASK
                    break
            else
            echo INVALID CHOICE && exit 3
        fi

done